const adversaryDatabase = {
    "Minions": [
        { name: "Giant Rat", tier: 1 },
        { name: "Jagged Knife Lackey", tier: 1 },
        { name: "Minor Treant", tier: 1 },
        { name: "Sellsword", tier: 1 },
        { name: "Skeleton Dredge", tier: 1 },
        { name: "Tangle Bramble", tier: 1 },
        { name: "Rotted Zombie", tier: 1 },
        { name: "Apprentice Assassin", tier: 2 },
        { name: "Conscript", tier: 2 },
        { name: "Cult Initiate", tier: 2 },
        { name: "Giant Recruit", tier: 2 },
        { name: "Elemental Spark", tier: 3 },
        { name: "Treant Sapling", tier: 3 },
        { name: "Fallen Shock Troop", tier: 4 },
        { name: "Hallowed Soldier", tier: 4 },
        { name: "Outer Realms Thrall", tier: 4 }
    ],
    "Social": [
        { name: "Courtier", tier: 1 },
        { name: "Merchant", tier: 1 },
        { name: "Petty Noble", tier: 1 },
        { name: "Courtesan", tier: 2 },
        { name: "Merchant Baron", tier: 2 },
        { name: "Royal Advisor", tier: 2 },
        { name: "Spy", tier: 2 },
        { name: "Monarch", tier: 3 }
    ],
    "Support": [
        { name: "Jagged Knife Hexer", tier: 1 },
        { name: "Cult Adept", tier: 2 },
        { name: "Demon of Avarice", tier: 3 },
        { name: "Greater Water Elemental", tier: 3 },
        { name: "Vault Guardian Gaoler", tier: 3 },
        { name: "Fallen Sorcerer", tier: 4 },
        { name: "Outer Realms Corrupter", tier: 4 }
    ],
    "Standard": [
        { name: "Glass Snake", tier: 1 },
        { name: "Harrier", tier: 1 },
        { name: "Bladed Guard", tier: 1 },
        { name: "Jagged Knife Bandit", tier: 1 },
        { name: "Skeleton Warrior", tier: 1 },
        { name: "Sylvan Soldier", tier: 1 },
        { name: "Shambling Zombie", tier: 1 },
        { name: "Elite Soldier", tier: 2 },
        { name: "Failed Experiment", tier: 2 },
        { name: "Spectral Guardian", tier: 2 },
        { name: "Vampire", tier: 3 }
    ],
    "Horde": [
        { name: "Giant Mosquitoes", tier: 1 },
        { name: "Pirate Raiders", tier: 1 },
        { name: "Swarm of Rats", tier: 1 },
        { name: "Tangle Bramble Swarm", tier: 1 },
        { name: "Zombie Pack", tier: 1 },
        { name: "Archer Squadron", tier: 2 },
        { name: "Demonic Hound Pack", tier: 2 },
        { name: "Electric Eels", tier: 2 },
        { name: "Zombie Legion", tier: 4 }
    ],
    "Ranged": [
        { name: "Archer Guard", tier: 1 },
        { name: "Jagged Knife Sniper", tier:1 },
        { name: "Skeleton Archer", tier: 1 },
        { name: "Chaos Skull", tier: 2 },
        { name: "Spectral Archer", tier: 2 },
        { name: "War Wizard", tier: 2 },
        { name: "Demon of Jealousy", tier: 3 },
        { name: "Vault Guardian Turret", tier: 3 },
        { name: "Hallowed Archer", tier: 4 }
    ],
    "Skulk": [
        { name: "Dire Wolf", tier: 1 },
        { name: "Jagged Knife Shadow", tier: 1 },
        { name: "Green Ooze", tier: 1 },
        { name: "Tiny Green Ooze", tier: 1 },
        { name: "Red Ooze", tier: 1 },
        { name: "Tiny Red Ooze", tier: 1 },
        { name: "Assassin Poisoner", tier: 2 },
        { name: "Cult Fang", tier: 2 },
        { name: "Giant Eagle", tier: 2 },
        { name: "Masked Thief", tier: 2 },
        { name: "Siren", tier: 2 },
        { name: "Stonewraith", tier: 2 },
        { name: "Demon of Despair", tier: 3 },
        { name: "Dire Bat", tier: 3 },
        { name: "Huge Green Ooze", tier: 3 }
    ],
    "Leader": [
        { name: "Head Guard", tier: 1 },
        { name: "Jagged Knife Lieutenant", tier: 1 },
        { name: "Pirate Captain", tier: 1 },
        { name: "Spellblade", tier: 1 },
        { name: "Young Dryad", tier: 1 },
        { name: "Master Assassin", tier: 2 },
        { name: "Giant Beastmaster", tier: 2 },
        { name: "Knight of the Realm", tier: 2 },
        { name: "Mortal Hunter", tier: 2 },
        { name: "Secret-Keeper", tier: 2 },
        { name: "Spectral Captain", tier: 2 },
        { name: "Demon of Hubris", tier: 3 },
        { name: "Dryad", tier: 3 },
        { name: "Head Vampire", tier: 3 },
        { name: "Arch-Necromancer", tier: 4 },
        { name: "High Seraph", tier: 4 }
    ],
    "Bruiser": [
        { name: "Bear", tier: 1 },
        { name: "Deeproot Defender", tier: 1 },
        { name: "Giant Scorpion", tier: 1 },
        { name: "Jagged Knife Kneebreaker", tier: 1 },
        { name: "Pirate Tough", tier: 1 },
        { name: "Stone Golem", tier: 1 },
        { name: "Berserker", tier: 2 },
        { name: "Demon of Wrath", tier: 2 },
        { name: "Giant", tier: 2 },
        { name: "Spectral Warrior", tier: 2 },
        { name: "Treant", tier: 2 },
        { name: "Demon of Rage", tier: 3 },
        { name: "Greater Fire Elemental", tier: 3 },
        { name: "Vault Guardian Sentinel", tier: 3 },
        { name: "Fallen General", tier: 4 },
        { name: "Hallowed Guardian", tier: 4 },
        { name: "Outer Realms Destroyer", tier: 4 }
    ],
    "Solo": [
        { name: "Ancient Dragon", tier: 2 },
        { name: "Lich", tier: 2 },
        { name: "Pit Fiend", tier: 3 },
        { name: "Solar Angel", tier: 3 },
        { name: "Kraken", tier: 4 },
        { name: "Tarrasque", tier: 4 }
    ]
};
