const adversaryDatabase = {
    "Minions": [
        { name: "Giant Rat", tier: 1, id: "giant_rat" },
        { name: "Jagged Knife Lackey", tier: 1, id: "jagged_knife_lackey" },
        { name: "Minor Treant", tier: 1, id: "minor_treant" },
        { name: "Sellsword", tier: 1, id: "sellsword" },
        { name: "Skeleton Dredge", tier: 1, id:"skeleton_dredge" },
        { name: "Tangle Bramble", tier: 1, id:"tangle_bramble" },
        { name: "Rotted Zombie", tier: 1, id: "rotted_zombie" },
        { name: "Apprentice Assassin", tier: 2, id:"apprentice_assassin" },
        { name: "Conscript", tier: 2, id:"conscript" },
        { name: "Cult Initiate", tier: 2, id:"cult_initiate" },
        { name: "Giant Recruit", tier: 2, id: "giant_recruit" },
        { name: "Elemental Spark", tier: 3, id:"elemental_spark" },
        { name: "Treant Sapling", tier: 3, id:"treant_sapling" },
        { name: "Fallen Shock Troop", tier: 4, id:"fallen_shock_troop" },
        { name: "Hallowed Soldier", tier: 4, id:"hallowed_soldier" },
        { name: "Outer Realms Thrall", tier: 4, id:"outer_realms_thrall" }
    ],
    "Social": [
        { name: "Courtier", tier: 1, id:"courtier" },
        { name: "Merchant", tier: 1, id:"merchant" },
        { name: "Petty Noble", tier: 1, id:"petty_noble" },
        { name: "Courtesan", tier: 2, id:"courtesan" },
        { name: "Merchant Baron", tier: 2, id:"merchant_baron" },
        { name: "Royal Advisor", tier: 2, id:"royal_advisor" },
        { name: "Spy", tier: 2, id:"spy" },
        { name: "Monarch", tier: 3, id:"monarch" }
    ],
    "Support": [
        { name: "Jagged Knife Hexer", tier: 1, id:"jagged_knife_hexer" },
        { name: "Cult Adept", tier: 2, id:"cult_adept" },
        { name: "Demon of Avarice", tier: 3, id:"demon_of_avarice" },
        { name: "Greater Water Elemental", tier: 3, id:"greater_water_elemental" },
        { name: "Vault Guardian Gaoler", tier: 3, id:"vault_guardian_gaoler" },
        { name: "Fallen Sorcerer", tier: 4, id:"fallen_sorcerer" },
        { name: "Outer Realms Corruptor", tier: 4, id:"outer_realms_corruptor" }
    ],
    "Standard": [
        { name: "Glass Snake", tier: 1, id:"glass_snake" },
        { name: "Harrier", tier: 1, id:"harrier" },
        { name: "Bladed Guard", tier: 1, id:"bladed_guard" },
        { name: "Jagged Knife Bandit", tier: 1, id:"jagged_knife_bandit" },
        { name: "Skeleton Warrior", tier: 1, id:"skeleton_warrior" },
        { name: "Sylvan Soldier", tier: 1, id:"sylvan_soldier" },
        { name: "Shambling Zombie", tier: 1, id:"shambling_zombie" },
        { name: "Elite Soldier", tier: 2, id:"elite_soldier" },
        { name: "Failed Experiment", tier: 2, id:"failed_experiment" },
        { name: "Spectral Guardian", tier: 2, id:"spectral_guardian" },
        { name: "Vampire", tier: 3, id:"vampire" }
    ],
    "Horde": [
        { name: "Giant Mosquitoes", tier: 1, id:"giant_mosquitoes" },
        { name: "Pirate Raiders", tier: 1, id:"pirate_raiders" },
        { name: "Swarm of Rats", tier: 1, id:"swarm_of_rats" },
        { name: "Tangle Bramble Swarm", tier: 1, id:"tangle_bramble_swarm" },
        { name: "Zombie Pack", tier: 1, id:"zombie_pack" },
        { name: "Archer Squadron", tier: 2, id:"archer_squadron" },
        { name: "Demonic Hound Pack", tier: 2, id:"demonic_hound_pack" },
        { name: "Electric Eels", tier: 2, id:"electric_eels" },
        { name: "Zombie Legion", tier: 4, id:"zombie_legion" }
    ],
    "Ranged": [
        { name: "Archer Guard", tier: 1, id:"archer_guard" },
        { name: "Jagged Knife Sniper", tier:1, id:"jagged_knife_sniper" },
        { name: "Skeleton Archer", tier: 1, id:"skeleton_archer" },
        { name: "Chaos Skull", tier: 2, id:"chaos_skull" },
        { name: "Spectral Archer", tier: 2, id:"spectral_archer" },
        { name: "War Wizard", tier: 2, id:"war_wizard" },
        { name: "Demon of Jealousy", tier: 3, id:"demon_of_jealousy" },
        { name: "Vault Guardian Turret", tier: 3, id:"vault_guardian_turret" },
        { name: "Hallowed Archer", tier: 4, id:"hallowed_archer" }
    ],
    "Skulk": [
        { name: "Dire Wolf", tier: 1, id:"dire_wolf" },
        { name: "Jagged Knife Shadow", tier: 1, id:"jagged_knife_shadow" },
        { name: "Green Ooze", tier: 1, id:"green_ooze" },
        { name: "Tiny Green Ooze", tier: 1, id:"tiny_green_ooze" },
        { name: "Red Ooze", tier: 1, id:"red_ooze" },
        { name: "Tiny Red Ooze", tier: 1, id:"tiny_red_ooze" },
        { name: "Assassin Poisoner", tier: 2, id:"assassin_poisoner" },
        { name: "Cult Fang", tier: 2, id:"cult_fang" },
        { name: "Giant Eagle", tier: 2, id:"giant_eagle" },
        { name: "Masked Thief", tier: 2, id:"masked_thief" },
        { name: "Siren", tier: 2, id:"siren" },
        { name: "Stonewraith", tier: 2, id:"stonewraith" },
        { name: "Demon of Despair", tier: 3, id:"demon_of_despair" },
        { name: "Dire Bat", tier: 3, id:"dire_bat" },
        { name: "Huge Green Ooze", tier: 3, id:"huge_green_ooze" }
    ],
    "Leader": [
        { name: "Head Guard", tier: 1, id:"head_guard" },
        { name: "Jagged Knife Lieutenant", tier: 1, id:"jagged_knife_lieutenant" },
        { name: "Pirate Captain", tier: 1, id:"pirate_captain" },
        { name: "Spellblade", tier: 1, id:"spellblade" },
        { name: "Weaponmaster", tier: 1, id: "weaponmaster" },
        { name: "Young Dryad", tier: 1, id:"young_dryad" },
        { name: "Master Assassin", tier: 2, id:"master_assassin" },
        { name: "Giant Beastmaster", tier: 2, id:"giant_beastmaster" },
        { name: "Knight of the Realm", tier: 2, id:"knight_of_the_realm" },
        { name: "Mortal Hunter", tier: 2, id:"mortal_hunter" },
        { name: "Secret-Keeper", tier: 2, id:"secret-keeper" },
        { name: "Spectral Captain", tier: 2, id:"spectral_captain" },
        { name: "Demon of Hubris", tier: 3, id:"demon_of_hubris" },
        { name: "Dryad", tier: 3, id:"dryad" },
        { name: "Head Vampire", tier: 3, id:"head_vampire" },
        { name: "Arch-Necromancer", tier: 4, id:"arch-necromancer" },
        { name: "High Seraph", tier: 4, id:"high_seraph" }
    ],
    "Bruiser": [
        { name: "Bear", tier: 1, id: "bear" },
        { name: "Brawny Zombie", tier: 1 , id: "brawny_zombie"},
        { name: "Deeproot Defender", tier: 1, id:"deeproot_defender" },
        { name: "Giant Scorpion", tier: 1, id:"giant_scorpion" },
        { name: "Jagged Knife Kneebreaker", tier: 1, id:"jagged_knife_kneebreaker" },
        { name: "Pirate Tough", tier: 1, id:"pirate_tough" },
        { name: "Skeleton Knight", tier: 1, id: "skeleton_knight"},
        { name: "Giant", tier: 2, id:"giant" },
        { name: "Giant Brawler", tier: 2, id: "giant_brawler"},
        { name: "Minotaur Wrecker", tier: 2, id: "minotaur_wrecker"},
        { name: "Shark", tier: 2, id: "shark"},
        { name: "Spectral Warrior", tier: 2, id:"spectral_warrior" },
        { name: "Treant", tier: 2, id:"treant" },
        { name: "Demon of Rage", tier: 3, id:"demon_of_rage" },
        { name: "Demon of Wrath", tier: 3, id: "demon_of_wrath"},
        { name: "Greater Earth Elemental", tier: 3, id: "greater_earth_elemental" },
        { name: "Greater Fire Elemental", tier: 3, id:"greater_fire_elemental" },
        { name: "Oak Treant", tier: 3, id: "oak_treant"},
        { name: "Vault Guardian Sentinel", tier: 3, id:"vault_guardian_sentinel" },
        { name: "Fallen General", tier: 4, id:"fallen_general" },
        { name: "Hallowed Guardian", tier: 4, id:"hallowed_guardian" },
        { name: "Outer Realms Abomination", tier: 4, id: "outer_realms_abomination" },
        { name: "Outer Realms Destroyer", tier: 4, id:"outer_realms_destroyer" },
        { name: "Perfected Zombie", tier: 4, id: "perfected_zombie" }
    ],
    "Solo": [
        { name: "Acid Burrower", tier: 1, id:"acid_burrower" },
        { name: "Cave Ogre", tier: 1, id: "cave_ogre" },
        { name: "Construct", tier: 1, id: "construct" },
        { name: "Minor Chaos Elemental", tier: 1, id: "minor_chaos_elemental" },
        { name: "Minor Fire Elemental", tier: 1, id: "minor_fire_elemental" },
        { name: "Minor Demon", tier: 1, id: "minor_demon"},
        { name: "Patchwork Zombie Hulk", tier: 1, id: "patchwork_zombie_hulk"},
        { name: "Battle Box", tier: 2, id: "battle_box" },
        { name: "Gorgon", tier: 2, id: "gorgon"},
        { name: "Juvenile Flickerfly", tier: 2, id: "juvenile_flickerfly"},
        { name: "Adult Flickerfly", tier: 3, id: "adult_flickerfly"},
        { name: "Hydra", tier: 3, id: "hydra" },
        { name: "Young Ice Dragon", tier: 3, id: "young_ice_dragon" },
        { name: "Fallen Warlord Realm-Breaker", tier: 4, id: "fallen_warlord_realm-breaker" },
        { name: "Fallen Warlord Undefeated Champion", tier: 4, id: "fallen_warlord_undefeated_champion" },
        { name: "Kraken", tier: 4, id:"kraken" },
        { name: "Oracle of Doom", tier: 4, id: "oracle_of_doom"},
        { name: "Volcanic Dragon Obsidian Predator", tier: 4, id:"volcanic_dragon_obsidian_predator" },
        { name: "Volcanic Dragon Molten Scourge", tier: 4, id:"volcanic_dragon_molten_scourge" },
        { name: "Volcanic Dragon Ashen Tyrant", tier: 4, id:"volcanic_dragon_ashen_tyrant" }
    ]
};
