const adversaryDatabase = {
    "Minions": [
        { name: "Giant Rat", tier: 1, id: "giant_rat" },
        { name: "Jagged Knife Lackey", tier: 1, id: "jagged_knife_lackey" },
        { name: "Minor Treant", tier: 1, id: "minor_treant" },
        { name: "Sellsword", tier: 1, id: "sellsword" },
        { name: "Skeleton Dredge", tier: 1, id:"skeleton_dredge" },
        { name: "Tangle Bramble", tier: 1, id:"tangle_bramble" },
        { name: "Rotted Zombie", tier: 1, id: "rotted_zombie" },
        { name: "Apprentice Assassin", tier: 2 },
        { name: "Conscript", tier: 2 },
        { name: "Cult Initiate", tier: 2 },
        { name: "Giant Recruit", tier: 2 },
        { name: "Elemental Spark", tier: 3 },
        { name: "Treant Sapling", tier: 3 },
        { name: "Fallen Shock Troop", tier: 4 },
        { name: "Hallowed Soldier", tier: 4 },
        { name: "Outer Realms Thrall", tier: 4 }
    ],
    "Social": [
        { name: "Courtier", tier: 1, id:"courtier" },
        { name: "Merchant", tier: 1, id:"merchant" },
        { name: "Petty Noble", tier: 1, id:"petty_noble" },
        { name: "Courtesan", tier: 2 },
        { name: "Merchant Baron", tier: 2 },
        { name: "Royal Advisor", tier: 2 },
        { name: "Spy", tier: 2 },
        { name: "Monarch", tier: 3 }
    ],
    "Support": [
        { name: "Jagged Knife Hexer", tier: 1, id:"jagged_knife_hexer" },
        { name: "Cult Adept", tier: 2 },
        { name: "Demon of Avarice", tier: 3 },
        { name: "Greater Water Elemental", tier: 3 },
        { name: "Vault Guardian Gaoler", tier: 3 },
        { name: "Fallen Sorcerer", tier: 4 },
        { name: "Outer Realms Corrupter", tier: 4 }
    ],
    "Standard": [
        { name: "Glass Snake", tier: 1, id:"glass_snake" },
        { name: "Harrier", tier: 1, id:"harrier" },
        { name: "Bladed Guard", tier: 1, id:"bladed_guard" },
        { name: "Jagged Knife Bandit", tier: 1, id:"jagged_knife_bandit" },
        { name: "Skeleton Warrior", tier: 1, id:"skeleton_warrior" },
        { name: "Sylvan Soldier", tier: 1, id:"sylvan_soldier" },
        { name: "Shambling Zombie", tier: 1, id:"shambling_zombie" },
        { name: "Elite Soldier", tier: 2 },
        { name: "Failed Experiment", tier: 2 },
        { name: "Spectral Guardian", tier: 2 },
        { name: "Vampire", tier: 3 }
    ],
    "Horde": [
        { name: "Giant Mosquitoes", tier: 1, id:"giant_mosquitoes" },
        { name: "Pirate Raiders", tier: 1, id:"pirate_raiders" },
        { name: "Swarm of Rats", tier: 1, id:"swarm_of_rats" },
        { name: "Tangle Bramble Swarm", tier: 1, id:"tangle_bramble_swarm" },
        { name: "Zombie Pack", tier: 1, id:"zombie_pack" },
        { name: "Archer Squadron", tier: 2 },
        { name: "Demonic Hound Pack", tier: 2 },
        { name: "Electric Eels", tier: 2 },
        { name: "Zombie Legion", tier: 4 }
    ],
    "Ranged": [
        { name: "Archer Guard", tier: 1, id:"archer_guard" },
        { name: "Jagged Knife Sniper", tier:1, id:"jagged_knife_sniper" },
        { name: "Skeleton Archer", tier: 1, id:"skeleton_archer" },
        { name: "Chaos Skull", tier: 2 },
        { name: "Spectral Archer", tier: 2 },
        { name: "War Wizard", tier: 2 },
        { name: "Demon of Jealousy", tier: 3 },
        { name: "Vault Guardian Turret", tier: 3 },
        { name: "Hallowed Archer", tier: 4 }
    ],
    "Skulk": [
        { name: "Dire Wolf", tier: 1, id:"dire_wolf" },
        { name: "Jagged Knife Shadow", tier: 1, id:"jagged_knife_shadow" },
        { name: "Green Ooze", tier: 1, id:"green_ooze" },
        { name: "Tiny Green Ooze", tier: 1, id:"tiny_green_ooze" },
        { name: "Red Ooze", tier: 1, id:"red_ooze" },
        { name: "Tiny Red Ooze", tier: 1, id:"tiny_red_ooze" },
        { name: "Assassin Poisoner", tier: 2 },
        { name: "Cult Fang", tier: 2 },
        { name: "Giant Eagle", tier: 2 },
        { name: "Masked Thief", tier: 2 },
        { name: "Siren", tier: 2 },
        { name: "Stonewraith", tier: 2 },
        { name: "Demon of Despair", tier: 3 },
        { name: "Dire Bat", tier: 3 },
        { name: "Huge Green Ooze", tier: 3 }
    ],
    "Leader": [
        { name: "Head Guard", tier: 1, id:"head_guard" },
        { name: "Jagged Knife Lieutenant", tier: 1, id:"jagged_knife_lieutenant" },
        { name: "Pirate Captain", tier: 1, id:"pirate_captain" },
        { name: "Spellblade", tier: 1, id:"spellblade" },
        { name: "Young Dryad", tier: 1, id:"young_dryad" },
        { name: "Master Assassin", tier: 2 },
        { name: "Giant Beastmaster", tier: 2 },
        { name: "Knight of the Realm", tier: 2 },
        { name: "Mortal Hunter", tier: 2 },
        { name: "Secret-Keeper", tier: 2 },
        { name: "Spectral Captain", tier: 2 },
        { name: "Demon of Hubris", tier: 3 },
        { name: "Dryad", tier: 3 },
        { name: "Head Vampire", tier: 3 },
        { name: "Arch-Necromancer", tier: 4 },
        { name: "High Seraph", tier: 4 }
    ],
    "Bruiser": [
        { name: "Bear", tier: 1, id: "bear" },
        { name: "Deeproot Defender", tier: 1, id:"deeproot_defender" },
        { name: "Giant Scorpion", tier: 1, id:"giant_scorpion" },
        { name: "Jagged Knife Kneebreaker", tier: 1, id:"jagged_knife_kneebreaker" },
        { name: "Pirate Tough", tier: 1, id:"pirate_tough" },
        { name: "Berserker", tier: 2 },
        { name: "Demon of Wrath", tier: 2 },
        { name: "Giant", tier: 2 },
        { name: "Spectral Warrior", tier: 2 },
        { name: "Treant", tier: 2 },
        { name: "Demon of Rage", tier: 3 },
        { name: "Greater Fire Elemental", tier: 3 },
        { name: "Vault Guardian Sentinel", tier: 3 },
        { name: "Fallen General", tier: 4 },
        { name: "Hallowed Guardian", tier: 4 },
        { name: "Outer Realms Destroyer", tier: 4 }
    ],
    "Solo": [
        { name: "Acid Burrower", tier: 1, id:"acid_burrower" },
        { name: "Cave Ogre", tier: 1, id: "cave_ogre" },
        { name: "Construct", tier: 1, id: "construct" },
        { name: "Ancient Dragon", tier: 2 },
        { name: "Lich", tier: 2 },
        { name: "Pit Fiend", tier: 3 },
        { name: "Solar Angel", tier: 3 },
        { name: "Kraken", tier: 4 },
        { name: "Tarrasque", tier: 4 }
    ]
};
